apiVersion: v1
kind: Secret
metadata:
  name: biblio-secrets
type: Opaque
stringData:
  JWT_SECRET: "secret123"
  # Adapter l'URL Ã  ton service PostgreSQL
  DATABASE_URL: "postgres://ton_user_postgres:ton_password@postgres:5432/bibliotheque"
