apiVersion: apps/v1
kind: Deployment
metadata:
  name: biblio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bibliotheque
  template:
    metadata:
      labels:
        app: bibliotheque
    spec:
      containers:
        - name: bibliotheque
          image: bibliotheque-api:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: biblio-secret
            - configMapRef:
                name: biblio-config
          volumeMounts:
            - name: sqlite-data
              mountPath: /app/database.sqlite
      volumes:
        - name: sqlite-data
          emptyDir: {}
